#!/bin/bash

# This script could resume the execution if it failed at some point to take advantage of the fact the qsubs files (ie the files for pbs torque) are already pregenerated by the workflow anyway even if it fails.

# Two Inputs: your specfic logs directory where your qsub files are. Make sure the names of your qsub files are specific to the parts of the workflow that you want to run.


logsdir=$1
#Example: logsdir="/projects/bioinformatics/HudsonSoybeanProject/VarCallingRuns/MattK_output_2016/Align.Soy_4small_samples/logs"
workflow_job=$2
#Example qsub*realVcall*

ls $logsdir/$workflow_job > qsubsscripts

readarray qsubs < qsubsscripts

rm qsubsscripts

i=0
while [ $i -lt ${#qsubs[@]}  ];
do
	qsub1=${qsubs[$i]}
	sed -i '/afterok/d' $qsub1
    	qsub $qsub1
	let i+=1
done

